apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multinet-cluster
spec:
  releaseName: multinet-cluster
  chart:
    spec:
      chart: multinet-cluster
      sourceRef:
        kind: HelmRepository
        name: lukso-charts
        namespace: flux-system
      version: v0.1.0
  interval: 1m0s
  install:
    remediation:
      retries: 3