apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lukso-network
spec:
  releaseName: lukso-network
  chart:
    spec:
      chart: lukso-network
      sourceRef:
        kind: HelmRepository
        name: lukso-charts
        namespace: flux-system
      version: v0.1.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    DOMAIN: l15.twy.gmbh
    TLS_SECRET_SUFFIX: l15-twy-gmbh