apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: lukso-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://chartmuseum.staging.lukso.dev/
  secretRef:
    name: chartmuseum-credentials