apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metacontroller
spec:
  releaseName: metacontroller
  chart:
    spec:
      chart: metacontroller
      sourceRef:
        kind: HelmRepository
        name: lukso-charts
        namespace: flux-system
      version: v2.0.10
  interval: 1m0s
  install:
    remediation:
      retries: 3