apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  prune: true
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./services/l15