apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    proxy:
      loadBalancerIP: 34.107.227.83