apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources
  - ../base/namespaces
  - ../base/kong
  - ../base/sealed-secrets
  - ../base/cert-manager
patchesStrategicMerge:
  - kong-values.yaml